import React, { Component } from 'react';
import List from '../../components/List';

export class ListPage extends Component {
  render() {
    const gameList = [
      {
        categories: {
          category: ['Party', 'Multiplayer', 'Action'],
        },
        slug: '1-2-switch',
        buyitnow: 'true',
        release_date: 'Mar 3, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '1-2-Switch',
        system: 'Nintendo Switch',
        id: 'QY7EtPDIW1WGVWSEkQ7ZVLvCFvonU-Wl',
        ca_price: '64.99',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000000141',
        video_link: 'h1OTBqODE64B-g16PJeQj6tifbVKl_v8',
        eshop_price: '49.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/oiM2QlLg9frNJhSWvFGmi5NAvEAGlYVx/_3d_ldcR3G0YQl590uHXZ89Jmouu5aS9.png',
        game_code: 'HACPAACCA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Action', 'Racing', 'Party', 'Multiplayer'],
        },
        slug: '10-second-run-returns-switch',
        buyitnow: 'false',
        release_date: 'Jan 25, 2018',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '10 Second Run RETURNS',
        system: 'Nintendo Switch',
        id: 'lB42IGr_QVMVWBuNGlQMrnCVt73o4TXM',
        ca_price: '7.65',
        number_of_players: 'up to 4 players',
        nsuid: '70010000007261',
        eshop_price: '6.54',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/306P-NbgQp1QkTDZphv8wN_LTYItaai4/Sa59XowxYAGVmItNAStVkdlJW_1H4UHY.png',
        game_code: 'HACNAJ6TA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Platformer', 'Puzzles'],
        },
        slug: '36-fragments-of-midnight-switch',
        buyitnow: 'false',
        release_date: 'Sep 14, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '36 Fragments of Midnight',
        system: 'Nintendo Switch',
        id: '-DSAjIl84izCTVqtY_-kl0Qhyb2WC8Od',
        number_of_players: '1 player',
        nsuid: '70010000001682',
        ca_price: '2.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/iO-59p9UJmgLgUSwbCRpLDWcKR4BjlJB/5W9GW5Iw7lxSJIQt2yUCMqxs7CgyY2us.png',
        game_code: 'HACNAHAXA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Sports', 'Simulation', 'Multiplayer', 'Arcade'],
        },
        slug: '3d-minigolf-switch',
        buyitnow: 'false',
        release_date: 'Feb 1, 2018',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '3D MiniGolf',
        system: 'Nintendo Switch',
        id: 'YO_D9j7bdFAT_iwa7MOrbk9OhI1mzECt',
        ca_price: '23.99',
        number_of_players: 'up to 4 players',
        nsuid: '70010000002619',
        eshop_price: '19.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/ZSiTIe6G_scjctTTP8BnRGXpcdhtpkPo/fuZREGvMCBFkziJYalTpKdDB9qnmRTwm.png',
        game_code: 'HACNAJAMA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Adventure', 'Simulation', 'Strategy'],
        },
        slug: '60-seconds-switch',
        buyitnow: 'false',
        release_date: 'Dec 18, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '60 Seconds!',
        system: 'Nintendo Switch',
        id: 'cRx1WkeyZt8m7HIOZzAE1KsO54U3O9F8',
        ca_price: '12.99',
        number_of_players: '1 player',
        nsuid: '70010000003896',
        video_link: '5kYXl1ZDE6BV4aJ-AwMPZqYRyxqwLFKw',
        eshop_price: '9.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/2JfMN6Uw6kHwewghHXmZrV_8lYY-tqnp/Bs55himwBFq0vLMdE1kVu83tC-qSTNf9.png',
        game_code: 'HACNALEWA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Platformer', 'Action', 'Arcade'],
        },
        slug: '88-heroes-98-heroes-edition-switch',
        buyitnow: 'true',
        release_date: 'Oct 12, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: '88 Heroes - 98 Heroes Edition',
        system: 'Nintendo Switch',
        id: 'y4jmcs2BhJ5LKsLtAw5TpYPStgo6ELu9',
        ca_price: '40.95',
        number_of_players: '1 player',
        nsuid: '70010000001213',
        eshop_price: '29.95',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/VSh86WnueY7wUBlNbnrI9kVBZEBaLTlk/z1Co8Vs2Az1HBIZyIn4JToqvMTcgSWsm.png',
        game_code: 'HACNAFLJA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Sports', 'Arcade'],
        },
        slug: 'aca-neogeo-2020-super-baseball-switch',
        buyitnow: 'false',
        release_date: 'Feb 8, 2018',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: 'ACA NEOGEO 2020 SUPER BASEBALL',
        system: 'Nintendo Switch',
        id: 'LA6MU56Y4NBdskB6YgYeQf-NsQyuQbEU',
        ca_price: '9.87',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000004033',
        eshop_price: '7.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/57D5eccOXL-c32_n2FVkm8NHlJjFg036/O_uEaOBkMj7306t2u9tg7b_QxBD-Doyb.png',
        game_code: 'HACNALHJA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['First Person', 'Arcade'],
        },
        slug: 'aca-neogeo-aero-fighters-2-switch',
        buyitnow: 'false',
        release_date: 'Aug 3, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: 'ACA NEOGEO AERO FIGHTERS 2',
        system: 'Nintendo Switch',
        id: 'VnsK6NZC_aA1IjjVybT04EYc6GxYp_gW',
        ca_price: '9.87',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000000372',
        eshop_price: '7.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/RMxHpNNN0n1RfNaG59ILlkNAJ89O53EF/EGLxZ1Y-UIqTLv6sZPznx-YX6N2xj5jF.png',
        game_code: 'HACNADS8A',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['First Person', 'Action', 'Arcade'],
        },
        slug: 'aca-neogeo-alpha-mission-ii-switch',
        buyitnow: 'false',
        release_date: 'Apr 6, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: 'ACA NEOGEO ALPHA MISSION II',
        system: 'Nintendo Switch',
        id: 'MII4HzzJUmKvdGz69ifvUaAk81yC0EqS',
        ca_price: '9.87',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000000222',
        eshop_price: '7.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/yvu068n6GtFzHLCWtU_2MQUDknSZJP_C/H_HlEyCx3Bz0yG7drPnMZga4EVDmM5FU.png',
        game_code: 'HACNACMYA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Fighting', 'Arcade'],
        },
        slug: 'aca-neogeo-art-of-fighting-switch',
        buyitnow: 'false',
        release_date: 'Sep 21, 2017',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: 'ACA NEOGEO ART OF FIGHTING',
        system: 'Nintendo Switch',
        id: 'Q8nUY4laZlEJwYtNmRhS9y_k1x1ZWnHy',
        ca_price: '9.87',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000000384',
        eshop_price: '7.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/lDOJDQ5tGAFhUUREEJTSjCSIi7b9Wv22/aIS-As9JZZcXdFrD2yG7ZIpBB-3yp1NS.png',
        game_code: 'HACNADTDA',
        buyonline: 'true',
      },
      {
        categories: {
          category: ['Fighting', 'Arcade'],
        },
        slug: 'aca-neogeo-art-of-fighting-2-switch',
        buyitnow: 'false',
        release_date: 'Jan 11, 2018',
        digitaldownload: 'false',
        free_to_start: 'false',
        title: 'ACA NEOGEO ART OF FIGHTING 2',
        system: 'Nintendo Switch',
        id: '5C7irg-7QsGx8710JGgGuDNgbBL6Zpgb',
        ca_price: '9.87',
        number_of_players: '2 players simultaneous',
        nsuid: '70010000004089',
        eshop_price: '7.99',
        front_box_art:
          'http://media.nintendo.com/nintendo/bin/u5ngIoIsGPxsv70kyw5nFWvi_63g63Ks/QFsaNJIsMFGah3JC95TypWfTgOxUeV2v.png',
        game_code: 'HACNALJQA',
        buyonline: 'true',
      },
    ];
    return <List games={gameList} />;
  }
}

export default ListPage;
